services:
  mailhog:
    image: mailhog/mailhog:v1.0.1
    ports:
      - "1025:1025"
      - "8025:8025"
    restart: 'unless-stopped'
  postgres:
    image: postgres:15
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: tpdb
      POSTGRES_USER: tpdbuser
      POSTGRES_PASSWORD: secret
volumes:
  postgres-data: